spring:
  application:
    name: tlias_web_management
  #mysql连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias_
    username: root
    password: 0993
  #配置文件大小
  servlet:
    multipart:
      max-file-size: 10MB #  文件最大
      max-request-size: 100MB # 请求最大
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰命名映射开关
    map-underscore-to-camel-case: true

    #配置事务管理日志规则
    logging:
      level:
          org.apache.ibatis.transaction.jdbc.JdbcTransaction: debug
#阿里云OSS配置
aliyun:
    oss:
        endpoint: https://oss-cn-beijing.aliyuncs.com
        bucketName: jw-javaweb
        region: cn-beijing
